### ISSUE TITLE
Add feature to trim recordings

### ISSUE THREAD

**Issue by ViktorKahu** [Bnyro/RecordYou#10]
The value of this app would increase if the above mentioned feature (trim start and/or end of recording) was added.

Also, a feature to automatically record all phone conversations (although unlikely and I'm not even sure if technically possible), would be awesome.

**Comment by Bnyro** [comment]
1. Is not planned because there's no official Android API for it.
2. Might be possible, however it's out of scope for the app which is meant to stay simple.
