### ISSUE TITLE
terrible place for mono and stereo

### ISSUE THREAD

**Issue by Wjxfi** [Bnyro/RecordYou#108]
### Steps to reproduce

idk

### Expected behavior

idk

### Actual behavior

https://user-images.githubusercontent.com/113500363/232255504-e671645f-5bea-4d76-9bbf-cb921befa7a4.mp4

### Record You version

0.5.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already resolved in debug builds.
