### ISSUE TITLE
Add MP3 format

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#11]
Hi, please add the MP3 format.

![Screenshot_2023-02-23-03-19-33-850_com.bnyro.recorder.jpg](https://user-images.githubusercontent.com/23485114/220790409-3dd7f6f5-557c-45bf-8ead-b54aa86a28f6.jpg)

Thanks 🙏

**Comment by Bnyro** [comment]
The Android `MediaRecorder` the app is using doesn't support mp3 as a codec, I'm afraid.
