### ISSUE TITLE
No wavy pattern when using wav format 

### ISSUE THREAD

**Issue by WhiCCX0** [Bnyro/RecordYou#111]
### Steps to reproduce

click settings
 Tick ​​Lossless audio record
 start recording

### Expected behavior

Wavy Pattern shows when using wav format 

### Actual behavior

 no Wavy Pattern on screen 

### Record You version

5.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
For Wav, a different audio recorder is being used, which doesn't support information about the amplitude the sane way as the usual recorder.
