### ISSUE TITLE
[Feature Request] Function to sort in ascending order according to x parameter

### ISSUE THREAD

**Issue by Terkyz** [Bnyro/RecordYou#112]
### Describe your suggested feature

Sometimes I record many audios or videos in a row, and I would like to see specifically the most recent one first in my list, maybe this is the desired behavior but in my case it is not so, because many times it is sorted in a random order. 

It would be great to have a list of filtering options such as "Alphabetical order", "Most recent first", "Oldest first", etc.

### Other details

By random order I mean that sometimes I record an audio and name it "Audio 1", and then I record another audio and rename it "Audio 2" and everything is fine until then, but when I record another audio (Audio 3) sometimes it is on top of Audio 1 or sometimes in the middle, which does not make sense.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately we can't sort the files by their creation date as that would require adding storage permissions to the app. The info we have are the name and the size, thus these options are available now for sorting.
