### ISSUE TITLE
Import/export recordings

### ISSUE THREAD

**Issue by quarkl8** [Bnyro/RecordYou#116]
### Describe your suggested feature

Have a button in the file manager tab to import/export recordings. This would make switching to the app from another recorder much easier.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't plan anything similar, you can choose a custom folder for the app to use in the settings which should be sufficient.

**Comment by quarkl8** [comment]
Oh I didn't notice that setting 😬 sorry!
