### ISSUE TITLE
Lock screen to end recording

### ISSUE THREAD

**Issue by mecuricat** [Bnyro/RecordYou#125]
### Describe your suggested feature

Toggle to end recording and save it when screen is locked.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however that's not planned for now from my side.
