### ISSUE TITLE
Sound wave animation covers the entire screen

### ISSUE THREAD

**Issue by adarsh1001** [Bnyro/RecordYou#135]
### Steps to reproduce

1. Open the app.
2. Start voice recording with default settings.
3. Even with a very normal loudness, the sound wave animation covers the entire screen.
![Screenshot_20230526-112544.png](https://github.com/Bnyro/RecordYou/assets/8820038/d3b50974-b26a-46da-bc9e-e9dc39bbe496)

### Expected behavior

The sound wave animation should be bounded to a certain extent and not cover the entire screen at normal loudness.

### Actual behavior

The sound wave animation covers the entire screen even at normal loudness.

### Record You version

5.2

### Android version

Android 12

### Other details

Device: LG Wing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
fixed in https://github.com/Bnyro/RecordYou/commit/f3afc137009e4e18389fb93880398dabcbdaef08
