### ISSUE TITLE
Google Play "Screen Recorder - Indico" App

### ISSUE THREAD

**Issue by rusty-snake** [Bnyro/RecordYou#140]
### Steps to reproduce

Open https://play.google.com/store/apps/details?id=com.bnyro.recorder

It does not look legitimate. Is it?

### Expected behavior

N/A

### Actual behavior

N/A

### Record You version

N/A

### Android version

N/A

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not legit and violates the license of the app. I'd kindly ask everyone who's able to to report it.
