### ISSUE TITLE
Don't open app when using quick settings

### ISSUE THREAD

**Issue by Commenter25** [Bnyro/RecordYou#142]
### Describe your suggested feature

When I press the quick settings action to start recording, it opens up the app immediately, overriding whatever I was doing, and asking for my PIN if I'm on the lock screen. I would much rather it just begin recording and stop recording from quick settings, which is much less intrusive and very frictionless. I know this is possible, as the proprietary app "Easy Voice Recorder" does this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's currently not planned, the quick settings shortcuts only exist for convenience but not really to be functional. When starting a recording, permissions for that need to be granted by the user first, so opening the app first makes sense.
