### ISSUE TITLE
Oled theme?

### ISSUE THREAD

**Issue by Toiletmason** [Bnyro/RecordYou#143]
### Describe your suggested feature

It seems like there is an oled theme in the example photos on the project page, but I can't seem to figure out a way to enable it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's currently only possible with Android 12+ using a very dark (black) wallpaper or using the black dark theme option in the Android settings, which only exists on Custom ROMs.

**Comment by Toiletmason** [comment]
@Bnyro So it's entirely based on You coloring. I guess that makes sense. I'm using oneui 5.1 Android 13 which uses AMOLED black theming, and use an amoled wallpaper but it doesn't seem to affect the coloring of you apps. I really hate the you color system if I'm being honest.

**Comment by Toiletmason** [comment]
@Bnyro So it's entirely based on You coloring. I guess that makes sense. I'm using oneui 5.1 Android 13 which uses AMOLED black theming, and use an amoled wallpaper but it doesn't seem to affect the coloring of you apps. I really hate the you color system if I'm being honest.

**Comment by Toiletmason** [comment]
@Bnyro That wasn't a dig at you, or the app my man.

**Comment by Bnyro** [comment]
I didn't interpret it like that, I just wanted to say that other apps might fit your use case better, since some ROMs don't adapt MD3 properly :)

**Comment by SuhasDissa** [comment]
#160
