### ISSUE TITLE
Live transcription

### ISSUE THREAD

**Issue by ThatOneCalculator** [Bnyro/RecordYou#144]
### Describe your suggested feature

Having the ability to (live) transcribe audio recordings would be great and would probably bring Record You up to par with Google's first party offering. 

### Other details

Could be implemented with whisper.cpp (they have Android/Java bindings) or Google Cloud Voice services

### Acknowledgements

- [X] #170
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Myzel394** [comment]
Google Pixel phones from 6 and onwards also support transcribing directly on the phone itself - I have no idea how it is implemented, but it does work in the Google Recorder. Maybe we could use this for Pixel devices?

**Comment by Bnyro** [comment]
With Google's STT service this could be integrated quite easily, but it's only available for devices using Google services and thus not usable for a lot of people like myself.
Whisper on the other hand would probably increase the app size by a lot and require the user to download some extra models or training data.
I'd accept PRs on that if it keeps the app size below 20MB, but I personally don't have interest on adding that.

**Comment by ThatOneCalculator** [comment]
What about whisper?

**Comment by Bnyro** [comment]
No plans for that currently.

**Comment by heckarman** [comment]
> With Google's STT service this could be integrated quite easily, but it's only available for devices using Google services and thus not usable for a lot of people like myself.

Even my phone do not have GMS, but Google STT app is a stand alone app and it doesn't require you to have GMS installed to run.
