### ISSUE TITLE
the microphone is not turned off during a pause

### ISSUE THREAD

**Issue by Wjxfi** [Bnyro/RecordYou#157]
### Steps to reproduce

activate https://www.f-droid.org/packages/com.aravi.dot/

turn on any mode and pause it

you see the microphone is still on. It only turns off when you turn off the recording completely.

### Expected behavior

my microphone turns off while paused.

### Actual behavior

my microphone stays on while paused.

### Record You version

5.3

### Android version

android 12 miui

### Other details

it bothers me a little bit

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're pausing the recorder in that time. Releasing it and re-creating would we bad for the app's performance and is therefore not planned.
