### ISSUE TITLE
Screen recordings should not be saved in the app's storage

### ISSUE THREAD

**Issue by matchboxbananasynergy** [Bnyro/RecordYou#16]
Currently, just like with audio recording, a screen recording will be saved in the app's internal storage by default. This is a great feature for audio recordings if you don't want to expose them to other apps with the storage permission.

That said, by virtue of the fact that Record You doesn't have a built in video player to be able to view actual screen recordings, it currently doesn't make sense to save a screen recording there.

This can be a significant issue if someone doesn't realize that and they record their screen, only to realize that the screen recording is "trapped" in the app's internal storage, where they can't view it or export it.

**Comment by Bnyro** [comment]
Another idea would be to try to add a very basic video player that will be used for videos instead of the audio player, or instead allow sharing the downloaded file to other apps.
