### ISSUE TITLE
Change AppShortcuts color

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#161]
### Describe your suggested feature

Please change the AppShortcuts color to blue. 💙

![Screenshot_2023-07-15-20-01-48-526_com miui home](https://github.com/Bnyro/RecordYou/assets/23485114/f2ebe375-257d-4cf7-8ed6-b9ce94f6f2a2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
I noticed that your icons are not purple, which is usually the case. I'm wondering if you could give me some more information to help us figure out why.

Specifically, I'd like to know what Android version you're using and if you're using any custom themes.
Additionally it would be helpful to know what your material you colour palette looks like.

**Comment by xmha97** [comment]
I'm using Xiaomi 11T (Android 13)
Using the default launcher and default theme)

**Comment by Bnyro** [comment]
We use some hardcoded colors for that, see https://github.com/Bnyro/RecordYou/blob/4f192501ca7b19ec574fe6ae05b0bf12f55bc370/app/src/main/res/values-night/colors.xml#L4

**Comment by xmha97** [comment]
> We use some hardcoded colors for that, see https://github.com/Bnyro/RecordYou/blob/4f192501ca7b19ec574fe6ae05b0bf12f55bc370/app/src/main/res/values-night/colors.xml#L4
> 
> I don't see why we should change that.

Because the app icon is purple.

**Comment by SuhasDissa** [comment]
I wonder why my phone shows them purple. (OneUI Samsung)
<img src="https://github.com/Bnyro/RecordYou/assets/64766434/ff4aa664-5175-4934-b488-93dc3a973efb" width="30%">
