### ISSUE TITLE
The app launch itself as soon as you swipe down Status Bar

### ISSUE THREAD

**Issue by JFMugen** [Bnyro/RecordYou#179]
### Steps to reproduce

- Add "Record Sound" button to Status bar

- Force Stop the app

- Swipe down the Status bar, and you will see the app launch itself. The app icon is always bright as well (which indicates it is running)

### Expected behavior

App stay off as long as I don't record anything. Icon is dimmed.

### Actual behavior

App stays on and the icon is bright. 

### Record You version

6.0

### Android version

8.0

### Other details

![image](https://github.com/Bnyro/RecordYou/assets/61559703/1607016a-8238-4e69-9c33-c9e9539d6893)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The app doesn't launch itself.
The shortcuts are only quick ways to open the app in the correct recording mode (audio/video).
It doesn't provide any functionality to start or stop a recording.

**Comment by JFMugen** [comment]
> The app doesn't launch itself.

But it does, aka "bug report". 

Just to be clear, it doesn't start video or audio recording, it just starts the app.

**Comment by JFMugen** [comment]
@Bnyro Here I record a video as well, hopefully it can help. 

https://github.com/Bnyro/RecordYou/assets/61559703/6449e47c-3223-498d-b216-22953d11c1f3

As you can see it is "Stopped" as long as I don't swipe down Status Bar. But once I do, it launches itself even tho I didn't touch the icon at all. The icon is bright as well instead of dimmed.
