### ISSUE TITLE
AppShortcuts

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#18]
Please add the app shortcuts below:
- Record Screen
- Record Sound

![Screenshot_2023-02-23-23-01-30-755_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221011219-424f514f-ebce-4b05-b6ee-ae36925bbbf9.jpg)

**Comment by Bnyro** [comment]
Nice launcher, which one is that?

**Comment by xmha97** [comment]
Thanks 🙏
It's Kvaesitso Launcher:
https://github.com/MM2-0/Kvaesitso

You can enable the "Themed Icons" on the Kvaesitso settings:
![Screenshot_2023-02-23-23-19-25-246_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221014576-f76019b6-3443-4c11-aef8-246a9219c0d6.jpg)

**Comment by xmha97** [comment]
> > Thanks 🙏
> > It's Kvaesitso Launcher:
> > https://github.com/MM2-0/Kvaesitso
> > 
> 
> bro, he has so many antifunctions....

I didn’t understand, please explain more.
