### ISSUE TITLE
IzzyOnDroid inclusion

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/RecordYou#2]
Hey @IzzySoft,
you probably didn't see that one coming ;)

Yet another app that would like to be included in your repo, this time it is about recording audio. It might get support for recording the screen too in the future, so it'd be possible the descriptions will need to be updated one day (if they don't update automatically, not sure anymore).
There are no screenshots yet, I'll probably add them within this week (adding changelogs is not planned).

Thank you in advance!
Cheers

**Comment by IzzySoft** [comment]
> you probably didn't see that one coming ;)

Not in my wildest dreams :rofl: This times you've been faster: my "app hunter" only found the app just a few minutes ago.

> so it'd be possible the descriptions will need to be updated one day

No prob: my updater will pull Fastlane along. But no screenshots even (first impression, 1.000 words and all that)? Please give me a ping when they're there, so I can enable them and give them an instant pull. Apart from that: added and will show up around 7 pm UTC, as usual :smiley: Thanks!

**Comment by Bnyro** [comment]
Hey, @IzzySoft,
I just added screenshots and also updated `short_description.txt` and `full_description.txt`, it would be awesome if you could pull them.
Thank you!

**Comment by IzzySoft** [comment]
Thanks! Activated & pulled, will take effect with the next sync then, as usual.

**Comment by Bnyro** [comment]
Hey @IzzySoft,
Since a week or something the permissions of `Record You` and `Connect You` are both shown as they would contain `ACCESS_NETWORK_STATE` although none of the apps have it declared in their `AndroidManifest.xml`. I'd be happy to get some insights why the permissions are shown as needed or why the apps could require it even though I'm not aware of it.
Thanks!

**Comment by IzzySoft** [comment]
@Bnyro run `aapt d badging *.apk` to check. If my repo reports them, they are there in the APK. So something dragged it in, i.e. one of your dependencies added it at build time (you can probably check the resulting Manifest in the build tree even).

```
package: name='com.bnyro.recorder' versionCode='6' versionName='3.3' platformBuildVersionName='13' platformBuildVersionCode='33' compileSdkVersion='33' compileSdkVersionCodename='13'
sdkVersion:'21'
targetSdkVersion:'33'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='android.permission.POST_NOTIFICATIONS'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='com.bnyro.recorder.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'
application-label:'Record You'
..
```

So something [something](https://github.com/google/ExoPlayer/search?q=ACCESS_NETWORK_STATE) maybe did it. Found the culprit I guess.

**Comment by Bnyro** [comment]
Oh, that seems to be the issue, thanks for spotting!
Could something like 
```
 <permission android:name="android.permission.ACCESS_NETWORK_STATE" tools:node="remove" />
```
remove the permission and thus resolve our issue?

**Comment by IzzySoft** [comment]
To my knowledge: yes, that's one of the theories. Maybe give it a try and we see? Just build an APK that way and run `aapt d badging *.apk` on it to see the results. If it works, we've got it solved (and I'm all ears to hear where you applied it then – as that might be a useful trick to show to other authors with similar issues). :smiley:

**Comment by Bnyro** [comment]
Indeed, it seems to work! :) The corresponding commit is https://github.com/Bnyro/RecordYou/commit/172585b4feaf5e08156f87f4b978c0768e18f7de.

**Comment by IzzySoft** [comment]
Ah! That's mega cool. So that line simply goes to the "main manifest" – hey, that's easy to remember even for me :laughing:

**Comment by IzzySoft** [comment]
Oh, PS: Repeat for Connect You then? :smiley:

**Comment by Bnyro** [comment]
> Oh, PS: Repeat for Connect You then? :smiley:
>
Done already :)
