### ISSUE TITLE
Obtainium and fdroid report different versions 

### ISSUE THREAD

**Issue by topcaser** [Bnyro/RecordYou#229]
### Steps to reproduce

Hi, I am using obtainium to download directly from github which works with most of my used apps. Unfortunately not with RecordYou. Obtainium says version 7.1 is newest whereas fdroid report 7.2. Is there something happened during your publishing process? 

### Expected behavior

Both app stores should report 7.2

### Actual behavior

Obtainium can't find 7.2 which means that a github process isn't followed 

### Record You version

7.1

### Android version

Android 14

### Other details

Graphenos, Pixel 8 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
This might be a bug in the Obtanium app. Therefore, it would be better to ask them about this.

**Comment by topcaser** [comment]
This is what obtainium team answered:

There is no 7.2 release, only a tag: https://github.com/you-apps/RecordYou/releases?q=7.2&expanded=true

**Comment by Bnyro** [comment]
There's a release, it's a GitHub issue that it doesn't show up.

**Comment by DarkCrypt** [comment]
> There's a release, it's a GitHub issue that it doesn't show up.

This is a GitHub sync issue and happens in many repos. Tags work fine. I've communicated to other devs about this and the quick solution is to force a re-sync.

Obtainium is great at pointing this out when it happens and is how I started noticing this bug.
