### ISSUE TITLE
Feature: Record Device Audio for screen recordings

### ISSUE THREAD

**Issue by salad612** [Bnyro/RecordYou#23]
Option to instead of or with microphone, record device audio

**Comment by xmha97** [comment]
Good idea 💡
Like DroidRec app

**Comment by Bnyro** [comment]
I know, but their code doesn't really have a structure and the code for recording screen and device audio is more than 1k lines...

**Comment by NeeRaj-2401** [comment]
Does device/system audio term includes on going call sounds too
I mean will it including recording on going system i.e. call audios recording too?

**Comment by NeeRaj-2401** [comment]
> Haven't tested but according to this maybe? ![audio](https://user-images.githubusercontent.com/121117961/221286610-6599a55d-49de-449b-939e-fa3d4afbb27f.png)

@salad612 is that ur system application or any 3rd party ?

**Comment by ElsAr4e** [comment]
Maybe you could also add the option to capture Unprocessed (Raw) audio even if you are using Android 8,9 (non-rooted devices):

https://www.youtube.com/watch?v=h52RLrs3ySw
