### ISSUE TITLE
Support for bluetooth headphones

### ISSUE THREAD

**Issue by Wjxfi** [Bnyro/RecordYou#24]
it records on a regular microphone in the phone

miui 13.0.5, android 12

**Comment by Bnyro** [comment]
This would require to add `android.permission.MODIFY_AUDIO_SETTINGS` to the app, I don't think it would be worth adding tbh.
@matchboxbananasynergy, opinion?

**Comment by Tobias-Lauerbach** [comment]
## I thought about opening a feature request, for a similar feature.

### Feature:
I wanted to ask for the ability to change or see which audio source/device is used (for example: wired headphones / Bluetooth / build in mic).

### Use case:
This would be useful if you want to make sure that the quality of the recording is good (for example as Backup audio for video recordings or just to select your build in mic if your headphones mic sucks)

(If needed, I would be happy to open this in a separate issue)

**Comment by akano12** [comment]
> mixplorer allows you to open any .apk file as code. You can use it to view the code of ordinary applications (not open-source)
> 
> To get the apk file you can use any app backup application
> 
> so you can get more information from other applications about the problem.
> 
> You can download the free mixplorer app below (it's actually paid, but they posted it here). https://t.me/mixplorer_channel

1- MiXplorer is free, it was never paid. (I do suggest you get it from original source instead of this channel)
2- You can't view the source of applications with any file manager, you'll have to de-obfuscate classes, fields, and methods which take a lot of time and patience.
3- Devs never said they don't know how to do what you asked for...... 😉

**Comment by Bnyro** [comment]
Adding support for bluetooth headphones was never the issue.
The issue is the permission that would need to be added in order for it to work.
And no, event if I didn't know how it works, I wouldn't reverse engineer a closed source app for it.
