### ISSUE TITLE
 Weblate Error

### ISSUE THREAD

**Issue by Tobias-Lauerbach** [Bnyro/RecordYou#28]
### Steps to reproduce

Open Weblate or follow this link:
https://hosted.weblate.org/projects/you-apps/record-you/#alerts

### Expected behavior

No Error

### Actual behavior

Error message: Merge Conflict ("Weblate konnte Upstream-Änderungen während der Aktualisierung des Repositorys nicht zusammenführen.")

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Should be fixed now, thanks for reporting.
