### ISSUE TITLE
feature req. Pause video

### ISSUE THREAD

**Issue by Wjxfi** [Bnyro/RecordYou#32]
### Describe your suggested feature

now you can only "end" the video recording.
But it's not comfortable

example of use:
Let's say that during a long recording I wanted to have some tea. I have to stop recording. I press the pause button. when I come back, I have to continue the existing recording. Otherwise it will have to be stitched together for a long time with proprietary video editors (if I completely stop recording and the app saves it as a file). this is a totally bad alternative to pausing. i can also think of lots of reasons to ""pause" and then continue the previous recording". for example just tired of recording and need a rest to continue recording. You get it. I need a pause. To be able to turn it on from the notification and from the app. There will be a "pause" button. And during the pause, in place of the "pause" button would be a "continue previous recording" button. The "stop recording" button should be near.

### Other details

I'm writing this in the middle of the night; I hope the text makes sense regardless.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already possible for audio recordings though.

**Comment by Bnyro** [comment]
Not planned currently.

**Comment by Bnyro** [comment]
Thanks for the dislike btw, I added support for it anyways.
