### ISSUE TITLE
Notification for audio recording

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#34]
### Describe your suggested feature

Please add a notification for the audio recording

![Screenshot_2023-02-25-13-16-16-306_com bnyro recorder](https://user-images.githubusercontent.com/23485114/221350521-f5c0c87a-4a9b-485a-bea3-d0c5500facdb.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that's needed, why would you want to leave the app while recording audio?

**Comment by xmha97** [comment]
Take a look at other voice recorder apps, they all show notifications when recording, so the notification is useful otherwise no one would have added it.

1. The notification helps us to know whether the recording is active or not without entering the app. (Without notification, someone might even forget to stop recording)

2. Having a notification (with buttons) helps us to pause and start the recording in other app and even on the lock screen, which makes it easy to use.

3. Having a notification helps prevent the app from closing. (Some old Huawei and Xiaomi phones don't keep apps in the background)

If this feature is added, if no one wants it, they can disable the notification.

**Comment by xmha97** [comment]
Thanks 👍

**Comment by xmha97** [comment]
Thanks, please add some category for screen recorder notification and voice recorder notification:

![Screenshot_2023-02-25-18-37-35-246_com.android.settings.jpg](https://user-images.githubusercontent.com/23485114/221364378-43055ea9-f76c-4f81-9227-61fa986abea4.jpg)

**Comment by Bnyro** [comment]
They're both using the same channel since I don't see a reason to create different ones for them.

**Comment by xmha97** [comment]
Ok 👌
