### ISSUE TITLE
Broken screen recordings

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/RecordYou#36]
### Steps to reproduce

Record the screen

### Expected behavior

The video should play

### Actual behavior

Instead this, I got a broken video that can't be played

### Record You version

3.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce. Did you try playing the video inside the app and outside with an external player?

**Comment by HotarunIchijou** [comment]
> Can't reproduce. Did you try playing the video inside the app and outside with an external player?

Yes, I did, but it doesn't work. Maybe it's because of custom ROM, which I use, but DroidRec works fine for me.

**Comment by HotarunIchijou** [comment]
So here's a video, which I get after screen recording, maybe it can be helpful

https://mega.nz/file/B7ZT2DxS#Uv_z5dBZX8BtVB0Ja3DfMgKqz9mBYHGO49k1MKciTM0

**Comment by HotarunIchijou** [comment]
I've changed ROM and now it seems to be working.
