### ISSUE TITLE
Add to F-Droid repo

### ISSUE THREAD

**Issue by vairag22** [Bnyro/RecordYou#39]
### Describe your suggested feature

Please add it to F-Droid repository. Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vairag22** [comment]
> The app is currently on the IzzyOnDroid F-Droid repository.

Yes, I know.

> If you use an F-Droid client like Neo Store or Droid-ify, that repo should be already enabled, or at least ready for you to enable. If you use the official F-Droid client, you'll need to add it.

F-Droid only hosts strictly FOSS apps therefore it is more trusted and widely used, compared to IzzyOnDroid. Please submit your app to that repository as well.

**Comment by Bnyro** [comment]
As I've already stated out on the TranslateYou repo:
`In my opinion, there are no real advantages of having the app on F-Droid instead of IzzyOnDroid: F-Droid is very slow in updating apps, it often takes up to a week while Izzy's repo syncs daily!`
If you have any good arguments why F-Droid is worth adding the app to apart from it being more trusted (which I personally wouldn't agree with), feel free to share them.

**Comment by vairag22** [comment]
> As I've already stated out on the TranslateYou repo: `In my opinion, there are no real advantages of having the app on F-Droid instead of IzzyOnDroid: F-Droid is very slow in updating apps, it often takes up to a week while Izzy's repo syncs daily!` If you have any good arguments why F-Droid is worth adding the app to apart from it being more trusted (which I personally wouldn't agree with), feel free to share them.

None.

I like keeping things minimal so having the convenience of using only one trusted source for my apps suits me well. But if the devs don't want to put their app on F-Droid then so be it, I don't want to force them.

**Comment by Bnyro** [comment]
Alright, thanks for the suggestion anyways!

**Comment by offa** [comment]
> That would require delegating the building and signing of the app to F-Droid. I'm not a developer of the app, so I don't know if this is something that's wanted at the moment.

This is – at least no longer – correct. F-Droid supports reproducible builds which will produce same binaries and use same signing keys.
