### ISSUE TITLE
Add finish notification

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#42]
### Describe your suggested feature

Hi,
Please show a notification on stopped recording.

![204384652-8fa5504a-ea50-44fa-a206-d523df456f22](https://user-images.githubusercontent.com/23485114/221732137-cfac24fd-1c3e-4f54-b61d-27812fd9ba4f.jpg)

Also add **Share** button and **Delete** button.

Thanks 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
Thanks but add the "Share" button.

![Screenshot_2023-03-03-17-44-58-739_com.bnyro.recorder.jpg](https://user-images.githubusercontent.com/23485114/222743175-8b6ea5bb-05c3-4249-8c5d-8fd6fcbf3d97.jpg)

**Comment by Bnyro** [comment]
I added it but it didn't seem to work properly so it's disabled for the current version.

**Comment by xmha97** [comment]
Ok
