### ISSUE TITLE
Video codec, bitrate and framerate selection 

### ISSUE THREAD

**Issue by ynm2ps2jfp87nkl** [Bnyro/RecordYou#45]
### Describe your suggested feature

Add a setting that allows the user to choose a codec (H.264, H.265 or even AV1 since new devices support it) and the corresponding bitrate, probably up to 200k

Edit: also bitrate - native to display (for 240hz devices), 120, 60 or 30

### Other details

Obviously both settings should be present in the options menu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Setting the framerate is not supported by the `MediaRecorder` API.
