### ISSUE TITLE
View recorded files in SAF

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#49]
### Describe your suggested feature

Please support SAF
I can't see this app on file manager.

![Screenshot_2023-03-03-01-23-38-279_com google android documentsui](https://user-images.githubusercontent.com/23485114/222569767-7195ca33-1ffb-40f3-9bce-5a9fd9dbf96a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
SAF is supported, the files are stored inside the app only by default.
