### ISSUE TITLE
Android quick tile

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#51]
### Describe your suggested feature

Please add two quick tile on the notification bar.
1. Record screen
2. Record sound

![Screenshot_2023-03-03-01-42-20-852_org mozilla fenix](https://user-images.githubusercontent.com/23485114/222570862-c38da739-7403-4a57-8b4f-7ac40114ba6f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You should use the app shortcuts instead.

**Comment by Bnyro** [comment]
I've added some now because it's not that of an effort, however they work exactly the same way as the launcher shortcuts!

**Comment by xmha97** [comment]
Thanks 🙏
