### ISSUE TITLE
Editing audio feature

### ISSUE THREAD

**Issue by heberjeur** [Bnyro/RecordYou#54]
### Describe your suggested feature

Trimming and editing of recorded audio on mobile can provide several advantages to users, including:
- can help to eliminate any unwanted sounds
- save time: Listen directly to what is needed
- user don't need another audio application to do that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not supported by the Android system API's. Since the app aims to be minimalistic, using third party libraries for it is out of scope for the app.
