### ISSUE TITLE
Recorded video and audio are not shown in the "recordings" tab, although they are visible in the file manager

### ISSUE THREAD

**Issue by Wjxfi** [Bnyro/RecordYou#57]
Recorded video and audio are not shown in the "recordings" tab, although they are visible in the file manager

### Steps to reproduce

record button
finish the record

### Expected behavior

ww

### Actual behavior

Instead of video and audio appearing, it says "nothing here".

### Record You version

3.3

### Android version

Android 12

### Other details

It worked before, something is broken in the new versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed with latest commit
