### ISSUE TITLE
Unprocessed audio from external Mic

### ISSUE THREAD

**Issue by mmBesar** [Bnyro/RecordYou#58]
### Describe your suggested feature

I need to record audio from external mic "3.5", without noise cancellation, unprocessed raw audio.
I'm on Rooted Lineage Android 11.
Thank you.

### Other details
EDIT_01:
I can do it with Open Camera with "Unprocessed" as an audio source, but I need audio only.
You may look into how Open Camera implemented the feature.
Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Feel free to test https://github.com/Bnyro/RecordYou/actions/runs/4326999346 and report back if it doesn't work.

**Comment by mmBesar** [comment]
@Bnyro Thank you.
Noise cancellation still working and audio quality not good!
I found it working fine with [Simple Voice Recorder](https://github.com/SimpleMobileTools/Simple-Voice-Recorder)

**Comment by Bnyro** [comment]
Happy to hear :)
