### ISSUE TITLE
Empty space below settings bottom sheet

### ISSUE THREAD

**Issue by Wjxfi** [Bnyro/RecordYou#65]
### Steps to reproduce

open settings

### Expected behavior

normal

### Actual behavior

A gray stripe appears at the bottom, which is not pretty. The settings menu has risen to the middle of the screen and should be at the bottom.
![322218](https://user-images.githubusercontent.com/113500363/222935224-896cff7e-8f73-4d3c-87d2-1dc173d7a342.jpg)

how it should work (taken from f-droid):
![322214](https://user-images.githubusercontent.com/113500363/222935227-65fe5232-bb58-4284-8a7d-e976e82b9585.jpg)

### Record You version

4.0

### Android version

android 12 miui 13.0.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately that seems to be a bug of the Material Design 3 library for compose. Since the bottom sheets are still experimental in the library, I doubt we can do anything except for waiting until they fix it.

**Comment by Bnyro** [comment]
Yes, it's been caused by adding more items to it now so that it height expanded.
