### ISSUE TITLE
Hide the microphone icon in the notification bar

### ISSUE THREAD

**Issue by AlbahrawyTiger** [Bnyro/RecordYou#70]
### Describe your suggested feature

![Screenshot_2023-03-07-16-12-32-82](https://user-images.githubusercontent.com/61330601/223450949-83f51f43-b882-40af-9e06-4c3cea6a9c26.jpg)
This is a feature that I haven't seen in any other voice recorder app and I wish it was implemented here!
How then?
I have an idea as far as I know, which is to make Record You run on top of the applications, so the microphone icon will disappear, because Record You is no longer running in the background, and therefore the system will not show the microphone icon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I dislike the idea because the microphone inside your screen has a purpose: indicating that an app is currently accessing your microphone.
Apart from that any system UI modifications would require root, which is a security issue itself.
Thus, not planned.
