### ISSUE TITLE
While recording or playing recordings the UI becomes very sluggish

### ISSUE THREAD

**Issue by pvagner** [Bnyro/RecordYou#73]
### Steps to reproduce

When I am recording or playing recorded files the UI of the RecordYou app is very sluggish on my device. When I keep it in the background it's recording fine and using other apps while the recording is in progress is working fine too.
This is considerably noticeable with new player controls where it's verry difficult to manipulate the position slider.
I am unable to figure it out, so I'm posting it here in case you have got an idea.

Thanks for all the hard work.

Greetings

Peter

### Expected behavior

The fact playback or recording is in progress should have minimal impact on the user experience.

### Actual behavior

The UI is really considerably slugish while recording or playback is in progress.

### Record You version

V4.0 (7)

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I didn't yet have any comparable issues with the app. Does the issue persist in release builds the same way as in debug builds? I've had some issues with other apps earlier that debug builds just didn't work well at all while release builds did.

**Comment by igorskyflyer** [comment]
I can confirm this issue as well - happening to me too, the weird thing is that when the app is recording the whole phone's UI is sluggish but the resulting screen recording is not. 😅

**Comment by Bnyro** [comment]
That seems to be an issue of the `MediaRecorder` library we use, I doubt we can change anything here.
