### ISSUE TITLE
Show units for video bitrate and audio sample rate

### ISSUE THREAD

**Issue by ishrq** [Bnyro/RecordYou#78]
### Describe your suggested feature

Show units for bitrate like mbps, kbps, etc. Likewise for audio sample rate.

Additionally, can specify the maximux accepted value.

E.g. Bitrate (Upto 120kbps)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The units are always the default ones of the unit, meaning for example bps for bitrates. Thus, I don't see a reason to add additional info about it, which would only be the case if we didn't use the standard units.
