### ISSUE TITLE
Add bookmark feature

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#9]
Please add the bookmark feature and add the bookmarks to the MP3 file, (like the Samsung Voice Recorder app)
Thanks.

**Comment by Bnyro** [comment]
I'm not sure of that, however I don't plan to add any bookmarking feature.

**Comment by xmha97** [comment]
> I'm not sure of that, however, I don't plan to add any bookmarking feature.

Hello @Bnyro 
I have reviewed many voice recorder apps.
So far the best app I have seen is your app:
- Simple appearance but beautiful at the same time
- Open source and no ads
- Support for landscape and dark theme

What I really need is a feature marker
If you don't want to spend time on this feature,
please reopen this issue so that people can see, discuss, and finally contribute.

As I said above, I tried many voice recorder apps, most apps have feature markers, and the bookmarks are stored in the app's database, not the file; This is not good because all bookmarks will be lost when the app is uninstalled and installed.

I checked the Samsung voice recorder app, I don't really understand where the markers are stored in the file and it seems impossible to implement the Samsung method.

I checked the Windows 11 voice recorder app and believe it implemented the simplest and best method.
This app saves markers in the Comments tag.
Most audio formats also have this tag.
I think this is a good method, please consider it.

![image](https://user-images.githubusercontent.com/23485114/220979844-4d1da31e-5445-4462-97d9-4e36d41384a5.png)

![image](https://user-images.githubusercontent.com/23485114/220979938-b59b378c-16ae-48c8-b15d-4bc06e481afa.png)

`Comments`=`23.44;22.36;21.24;20.12;18.72;17.28;16.16;15.56;14.92;13.68;12.16;10.44;8.72;6.6;3.28;`

Sorry for my bad English.
Thanks.

**Comment by Bnyro** [comment]
I got your points and arguments, however I don't think this would fit the app well, even if someone else created a PR for it (I wouldn't reject it to not waste the work spent on it, but I'd prefer keeping the app simple). Adding support for it would require adding a third party dependency (if there even is one), and I don't think that fits the minimalism of the app well.
