### ISSUE TITLE
[Feature Request] Show screen taps on screen recording

### ISSUE THREAD

**Issue by user8446** [Bnyro/RecordYou#91]
### Describe your suggested feature

It would be an improvement if RecordYou showed screen taps when recording. This would greatly help when someone is watching a video to know what the user is doing especially for bug reporting, tech support, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately that's not possible with the system APIs we're using. However, you can enable the option "Show taps" inside the developer option of your phone, which will cause them to be recorded inside Record You too.
