### ISSUE TITLE
Video and audio running out of sync during screen recording

### ISSUE THREAD

**Issue by schulle4u** [Bnyro/RecordYou#97]
### Steps to reproduce

1. Activate microphone in the settings, then Switch to screen recording mode.
2. Start a recording.
3. Do something to cause screen movement, switch apps or similar tasks.
4. Finish the recording after approximately 2 minutes.

### Expected behavior

Video and audio tracks should stay in sync in the resulting video file.

### Actual behavior

Audio and video tracks loose their synchronisation shortly after beginning of the file. While the audio plays normally, the video runs after, sometimes even freezes. Tested with several video players to make sure this isn't a playback issue. 

### Record You version

v5.0 (10)

### Android version

13

### Other details

Google Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ingroxd** [comment]
Could someone actually reproduce the bug?

I tried with Android 13, Record You 5.3 on a Pixel 6 and my recordings go just fine.

@schulle4u Did you by any chance tried to change your video player?

**Comment by Bnyro** [comment]
I for myself couldn't reproduce it either.

**Comment by schulle4u** [comment]
I just did a clean install of the latest version, and now it appears to work. Either this has been fixed by accident or my device had some kind of configuration hiccups during my last test. Sorry for any headache, I'm closing this for now. 🙂

**Comment by Bnyro** [comment]
No worries, great it's working now!
