### ISSUE TITLE
Feature to change frame rate (FPS) & translation update

### ISSUE THREAD

**Issue by Alexandru51** [Bnyro/RecordYou#98]
Add a feature that it can change the frame rate (FPS) in screen recorder.
However, i modified and improved the romanian translation, because some words we're not translated correctly and added for new words. So yeah, that's what i can say😅

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Alexandru51** [comment]
Oh, and forgot to say that, you must also add "internal sound" at screen recorder option

**Comment by Bnyro** [comment]
Setting the FPS is not possible with the Android MediaRecorder.

**Comment by Alexandru51** [comment]
Oh, well, understandable
